### PR TITLE
fix for duplicate commodities not working

### PR DESCRIPTION
**Pull request by glavery**

### CODE REVIEW

**Comment by trbateman** [comment]
@glavery Is this for the problem in production? Did we find out why staging, development and local environments aren't affected? Ideally we should know why we need a code change.

**Comment by glavery** [comment]
> @glavery Is this for the problem in production? Did we find out why staging, development and local environments aren't affected? Ideally we should know why we need a code change.

no it is not specifically for the issue on production. it is for another critical issue. i just think that it might resolve the issue on production. as to why production has this issue and ther envs don’t i do not know the asnwer to that

**Comment by glavery** [comment]
> New bug identified
> https://uktrade.atlassian.net/jira/software/projects/UH/boards/117?selectedIssue=UH-435

I can't replicate that. works fine for me on dev, staging, local and prod

**Comment by glavery** [comment]
> > New bug identified
> > https://uktrade.atlassian.net/jira/software/projects/UH/boards/117?selectedIssue=UH-435
> 
> I can't replicate that. works fine for me on dev, staging, local and prod

It turns out that the steps to replicate was missing a step. which is why i could not replicate it.
that is now fixed in a separate branch 
PR is https://github.com/uktrade/dit-helpdesk/pull/180

**Comment by trbateman** [comment]
Met with Glen and Mark to discuss the impact of the code before merging.

**Pull request merged**
